# Generated by Django 5.1 on 2024-09-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daikamoku_app', '0002_user_email_confirmed_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
