# Generated by Django 5.1 on 2024-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daikamoku_app', '0003_remove_user_email_confirmed_delete_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe una cuenta con este correo electrónico.'}, max_length=255, unique=True),
        ),
    ]
