# Generated by Django 5.1 on 2024-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daikamoku_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con ese correo electrónico.'}, max_length=255, unique=True),
        ),
    ]
